version: '3.2'

services:
  app:
    build:
      context: library_back
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app
    volumes:
      - ./library_back:/code
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:13
    restart: always
    command: -p 5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db

    expose:
      - 5433
    ports:
      - 5433:5432
    networks:
      - app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app:
    driver: bridge