version: '3.2'

services:
  db:
  image: postgres:13
  restart: always
  command: -p 5433
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=library_db

  expose:
    - 5433
  ports:
    - 5433:5432
  networks:
    - app
  volumes:
    - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: library_back
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app
    volumes:
      - ./library_back:/code
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5433
  
  front:
    build:
      context: library_front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - app
    networks:
      - app
    volumes:
      - ./library_front:/code

volumes:
  postgres_data:

networks:
  app:
    driver: bridge